export YDOTOOL_SOCKET=/run/user/1000/.ydotool_socket

export PATH=$HOME/bin:/usr/local/bin:$PATH

# krew for kubectl
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# allows history between iex sessions
export ERL_AFLAGS="-kernel shell_history enabled"

export HISTCONTROL=ignoredups

source ~/.zshenv_private
